### PR TITLE
Translation for the sending usage statistics

### PR DESCRIPTION
**Pull request by PEPERSO**
I've noticed that the "Custom bangs", and same for the shortcut section at the end of the preferences is not in the translation file, I'll be happy to translate it if you add it there :)

### CODE REVIEW

**Comment by PalmerAL** [comment]
Thanks for translating!

For the usage statistics, you need to copy the entire HTML string from the en-US file:
```
"settingsUsageStatisticsToggle": {
      "unsafeHTML": "Send usage statistics (<a href=\"https://github.com/minbrowser/min/blob/master/docs/statistics.md\">More info</a>)"
    },
```

And replace "send usage statistics" and "more info" with translations.

You're right about custom bangs, I'll fix that.

Translating the keyboard shortcut names isn't supported at the moment; see issue #1322.

**Comment by PEPERSO** [comment]
Alright, sorry for the missing URL, it's done now let me know when you add the custom bangs, I'll translate it too :)

**Comment by PalmerAL** [comment]
You need the `unsafeHTML` part too; it's probably easiest to just copy the whole code block from the last comment, exactly as it's written.

I'll update this branch so that it has places to add the custom bang strings.

**Comment by PEPERSO** [comment]
Oops, sorry, I'll remember for next translations !

**Comment by PalmerAL** [comment]
I updated the branch, they should be there already!

**Pull request closed without merging**
