### PR TITLE
Solution for sandbox bug in Debian based distro

### PR DESCRIPTION
**Pull request by eltonfabricio10**
https://github.com/minbrowser/min/issues/778

### CODE REVIEW

**Comment by PalmerAL** [comment]
I think this should have been fixed already by 99c406dbf862b5fa235bbba0af751c4e752624e7 (so for all releases >=1.11.1); are you still seeing this issue in the latest version?

**Comment by eltonfabricio10** [comment]
Yes, it still has the problem in the latest version.

**Comment by EchedeyLR** [comment]
@PalmerAL is there any update for this to be merged?

**Comment by PalmerAL** [comment]
Yeah, I guess it's fine to merge this. The package generator [already does this same thing](https://github.com/electron-userland/electron-installer-common/blob/bd3f8cafff92e7bcbdb8ca4bccd9ce2c07911613/src/sandboxhelper.js#L33), so I'm confused why this is necessary, but I guess it's probably not worth the time to investigate.

**Pull request merged**
