### PR TITLE
lint with some semi colons

### PR DESCRIPTION
**Pull request by Milo123459**
Referring to palmers comment in my last lint PR, he said "The lack of semicolons in the JS files is confusing me!" so I took matters into my own hand and now we are using semistandard 🎉

### CODE REVIEW

**Comment by shalva97** [comment]
why would lack of semicolons be confusing? is not it just a boring boilerplate code that is only useful for interpreter?

**Comment by Milo123459** [comment]
Ask palmer, also, semicolons are amazing :)

**Comment by shalva97** [comment]
why are they amazing?

**Comment by Milo123459** [comment]
Who knows

**Comment by PalmerAL** [comment]
I wasn't being too serious with that comment, sorry for not making that more clear.

Anyway, I think the style is good enough for now. Maybe there is a more ideal style (and maybe semicolons would be better), but it's not worth reformatting everything continously in search of something better.

**Pull request closed without merging**
