### PR TITLE
add setting to disable task overlay on task switch

### PR DESCRIPTION
**Pull request by toraora**
This adds a setting to disable the task overlay popup on task switch (default mod+[ and mod+]). 

For me, it's visually jarring and doesn't provide much utility (especially in dark mode, the selected tab is barely visible).

### CODE REVIEW

**Comment by PalmerAL** [comment]
I'm not sure adding a setting for this is the right idea - it seems more like a design flaw that we should fix in general. Maye if we made the animation less distracting? Another option would be to not show anything if you press and release the keys immediately, but show the task overlay if you hold the keys down for a bit.

The thing about dark mode sounds like a bug, I've created a new issue for it: #470.

**Comment by toraora** [comment]
I like the latter idea. Maybe after holding the keys for long enough, you enter a mode where you can cycle through tasks in the overlay by repeating the key patterns (I think this is how the current implementation was intended to feel)

**Comment by PalmerAL** [comment]
BTW, I've fixed the bug with dark mode in 02d1276661fce45dc61f49bcb6b99ac9f231b104.

**Comment by PalmerAL** [comment]
The animation has been removed completely in #784, so this shouldn't be necessary any more.

**Pull request closed without merging**
