### PR TITLE
Add RPM builds, update main.build.js

### PR DESCRIPTION
**Pull request by shirshendu**
Require grunt-electron-installer-redhat
Create tasks for i686 and x86_64 RPM builds

### CODE REVIEW

**Comment by PalmerAL** [comment]
I'm having trouble getting this to build on OS X. ```rpmbuild``` requires a ```groups``` option, so adding this fixes the first problem:

```
group: "Applications/Internet"
```

but then I get this error:
```
Warning: Error executing command (1): 
rpmbuild -bb /var/folders/l4/q7gr5nt154lbfrsyngfx9bcc0000gn/T/electron-116322-67630-juii9f/min_1.1.2_i686/SPECS/min.spec --target i686
error: Unable to open temp file.
    Unable to open temp file.
 Use --force to continue.
```

I'm not sure what to do about this. I guess this is a bug in ```electron-installer-debian```.

**Comment by shirshendu** [comment]
Thanks for your input. It was building and installing on Fedora 23, and I didn't think to check properly on other platforms. Let me do this:
[ ] find an OSX machine and try and get to the bottom of this (gut feeling is that its an rpmbuild configuration issue)
[ ] Try building RPMs from Fedora, RHEL, OSX and windows
[ ] install should work on Fedora as well as RHEL (start with fresh boxes so as to figure out any other library dependencies)

**Comment by shirshendu** [comment]
The documentation for `electron-installer-redhat` does not mention OSX at all. Could you please let me know where you are installing rpmbuild from? (Homebrew/macports and which recipe)

**Comment by PalmerAL** [comment]
Homebrew - ```brew install rpm```.

**Comment by kajuberdut** [comment]
Looks like this pull request has been dead about two years and the referenced issue #219 hasn't moved in a year. Any chance somebody has working rpm build instructions using Alien or grunt-electron-installer-redhat?

**Comment by PalmerAL** [comment]
I tried this again with a newer version of `electron-installer-redhat`, and everything seems to be working now, so I've added an RPM build script in 31384f19f8966aa23b2c4f89a3d1a4ce2d2452fa. A prebuilt RPM will be available starting with the next release.

**Pull request closed without merging**
