### PR TITLE
Update tabBar.js

### PR DESCRIPTION
**Pull request by idAlencar**
the idea is to show where people are researching

### CODE REVIEW

**Comment by PalmerAL** [comment]
I'm not sure I understand the reason for this. I'm assuming that most people change their search engine rarely (or never), and so you would most likely already know where your search is going to go. Is there another scenario I'm missing?

**Comment by idAlencar** [comment]
most people just open the browser and search. I work daily with people who barely know what a browser is, I realized that google chrome became popular because it had the search service name in the browser name. the most talked about phrase about navigation is "open a google". the idea is that the person will see in the first contact where he will search

**Comment by idAlencar** [comment]
the goal is to display the message "search on (search server) or type an address" in the bar, making it clear in the first contact where it will be searched

**Comment by PalmerAL** [comment]
I think most people who don't know what a browser is won't be using Min, so that's less of a concern for us than it is for Chrome. Given that, and the fact that this would require re-translating this string, I'm inclined not to do it. If we get more feedback in the future that this is an issue, I'd be happy to reconsider it.

**Comment by idAlencar** [comment]
I understand your side, I just want to leave the idea and the path that many projects sinned, develop for developers or who knows, the big projects (windows, mac, chrome, firefox, office etc.) were great because they reached simple people (they don't know a browser). this I would like to see in Min, a browser for anyone to install and use

**Pull request closed without merging**
