### PR TITLE
new language French

### PR DESCRIPTION
**Pull request by cubmann**
{
    "name": "French (France)",
    "identifier": "fr-FR",
    "translations": {
        /* Context menu items
        these are the items displayed in the menu when you right-click on a page
        */
        "openInNewTab": "Ouvrir un nouvel onglet",
        "openInNewPrivateTab": "Ouvrir un onglet de navigation privée",
        "viewImage": "Voir l'image",
        "openImageInNewTab": "Ouvrir l'image dans un nouvel onglet",
        "openImageInNewPrivateTab": "Ouvrir l'image dans un onglet de navigation privée",
        "saveImageAs": "Enregistrer l'image sous",
        "searchWith": "Rechercher avec %s", //%s will be replaced with the name of the current search engine
        "copyLink": "Copier le lien",
        "copy": "Copier", //this is a verb (as in "copy the currently-selected text")
        "paste": "Coller",
        "goBack": "Retour",
        "goForward": "Avancer",
        "inspectElement": "Inspecter l'élément",
        /* searchbar */
        "DDGAnswerSubtitle": "Réponse", //this is a noun - it is used as a subtitle when displaying Instant Answers from DuckDuckGo in the searchbar
        "suggestedSite": "Site suggéré", //this is used to label suggested websites from the DuckDuckGo API,
        "resultsFromDDG": "Résultats de DuckDuckGo", //this is used as a label to indicate which results come from DuckDuckGo's API
        "taskN": "Tache %n", //this is used as a way to identify which tab a task is in "task 1", "task 2", ...
        "hostsFileEntry": "Fichier local", //this is a label used to indicate that a result is coming from the user's host file        
        /* custom !bangs
        these are some of the items that show up when you press ! in the searchbar.
        Each one of these strings describes what the command will do when you run it. */
        "viewSettings": "Voir les réglages",
        "takeScreenshot": "Prendre une capture d'écran",
        "clearHistory": "Vider l'historique",
        "switchToTask": "Changer de tache",
        "createTask": "Créer une tache",
        "moveToTask": "Déplacer cette tache à cet onglet",
        "searchBookmarks": "Rechercher des signets",
        /* navbar */
        "enterReaderView": "Entrer en mode lecteur",
        "exitReaderView": "Sortir du mode lecteur",
        "emptyReadingListTitle": "Votre liste de lecture est vide",
        "emptyReadingListSubtitle": "Les articles que vous ouvrez en mode lecteur sont sauvegardés ici pendant 30 jours.",
        "newTabLabel": "Nouvel onglet", //this is a noun, used for tabs that don't have a page loaded in them yet
        "connectionNotSecure": "Votre connection n'est pas sécurisée.",
        "searchbarPlaceholder": "Recherchez et entrez une adresse",
        "privateTab": "Onglet privé",
        "newTabAction": "Ajouter un onglet", //this is a verb, used to label a button that adds a tab to the tabstrip when clicked
        /* task overlay */
        "viewTasks": "Voir les taches",
        "newTask": "Nouvelle tache", //"new" is a verb - it is used for a button at the bottom of the task overlay
        "defaultTaskName": "Tache %n", //this is the name used for newly-created tasks; %n is replaced with a number ("task 1", "task 2", etc)
        /* find in page toolbar */
        "searchInPage": "Rechercher dans la page", //this is used as the placeholder text for the textbox in the find in page toolbar
        "findMatchesSingular": "%i de %t match", //this and the next label are used to indicate which match is currently highlighted
        "findMatchesPlural": "%i de %t matches",
        /* Focus mode */
        "isFocusMode": "Vous êtes en mode Focus.",
        "closeDialog": "OK", //used as a label for the button that closes the dialog
        "focusModeExplanation1": "En mode focus, tous les onglets à l'exeption de celui actif sont cachés, et vous pouvez créer de nouveaux onglets.",
        "focusModeExplanation2": "Vous pouvez quitter le mode focus en désactivantla fonction \"focus mode\" dans le menu vue.",
        /* pages/crash/index.html */
        "crashErrorTitle": "Il y a eu un problème.",
        "crashErrorSubtitle": "Il y a eu un problème en affichant cette page.",
        /* pages/error/index.html */
        "errorPagePrimaryAction": "Essayer encore",
        "serverNotFoundTitle": "Serveur non trouvé",
        "serverNotFoundSubtitle": "Min ne peut pas trouver ce site internet.",
        "archiveSearchAction": "Rechercher sur archive.org",
        "sslErrorTitle": "Ce site n'est pas disponible",
        "sslErrorMessage": "Min ne peut pas établir une connection sécurisée avec ce site.",
        "dnsErrorTitle": "Site non trouvé",
        "dnsErrorMessage": "Il y a eu un problème DNS avec ce site.",
        "offlineErrorTitle": "Vous êtes hors-ligne",
        "offlineErrorMessage": "Reconnectez vous à internet et réessayez.",
        "genericConnectionFail": "Min ne peut pas se connecter à ce sit internet.",
        "sslTimeErrorMessage": "Min ne peux pas établir une connection sécurisée avec ce site. Merci de vérifier que votre horloge est bien réglée.",
        "addressInvalidTitle": "Cette adresse est invalide.",
        "genericError": "Il y a une erreur",
        /* pages/phishing/index.html */
        "phishingErrorTitle": "Ce site peut vous nuir.",
        "phishingErrorMessage": "Ce site peux essayer de vous dérober vos informations personnelles, comme un mot de passe ou des informations bancaires",
        "phishingErrorVisitAnyway": "Visiter quand même",
        "phishingErrorLeave": "Quitter ce site",
        /* pages/sessionRestoreError/index.html */
        "sessionRestoreErrorTitle": "Il y a eu une erreur",
        "sessionRestoreErrorExplanation": "Vos onglets sauvegardés n'ont pas pu être restaurés correctement.",
        "sessionRestoreErrorBackupInfo": "Nous avons enregistrés une sauvegarde de vos données à cette localisation: %l.", //%l will be replaced with a path to a file
        "sessionRestoreErrorLinkInfo": {
            "unsafeHTML": "Si cette erreur continue à se produire, merci d'ouvrir un ticket: <a href=\"https://github.com/minbrowser/min\" target=\"_blank\">ici</a>."
        },
        /* pages/settings/index.html */
        "settingsPreferencesHeading": "Préférences",
        "settingsRestartRequired": "Vous devez redémarrer pour appliquer les changements.",
        "settingsPrivacyHeading": "Contenu bloqué",
        "settingsContentBlockingToggle": "Traceurs et publicités",
        "settingsBlockScriptsToggle": "Scripts bloqués",
        "settingsBlockImagesToggle": "Images bloquées",
        "settingsEasyListCredit": {
            "unsafeHTML": "Basé sur EasyList et EasyPrivacy, sans élément caché. Créé par <a target=\"_blank\" href=\"https://easylist.to/\">Les auteurs de EasyList</a> - <a target=\"_blank\" href=\"https://creativecommons.org/licenses/by-sa/3.0/legalcode\">voir la licence</a>."
        },
        "settingsAppearanceHeading": "Apparence",
        "settingsDarkModeToggle": "Activer le mode nuit",
        "settingsHistoryButtonToggle": "Activer le boutton navigation",
        "settingsSwipeNavigationHeading": "Swipe navigation", //same on french
        "settingsSwipeNavigationToggle": "Activer swipe pour changer de page.",
        "settingsSearchEngineHeading": "Moteur de recherche",
        "settingsDefaultSearchEngine": "Choisir un moteur de recherche par défaut:",
        "settingsDDGExplanation": "Définir DuckDuckGo comme moteur de recherche par défaut pour voir instantanément des résulats dans la barre de recherche.",
        "settingsKeyboardShortcutsHeading": "Raccourcis clavier",
        "settingsKeyboardShortcutsHelp": "Tapez \"mod\" pour utiliser la commande ou la touche de controle.",
        /* app menu */
        "appMenuFile": "Fichier",
        "appMenuNewTab": "Nouvel onglet",
        "appMenuNewPrivateTab": "Nouvel onglet de navigation privée",
        "appMenuNewTask": "Nouvelle tâche",
        "appMenuSavePageAs": "Enregistrer la page sous",
        "appMenuPrint": "Imprimer",
        "appMenuEdit": "Editer",
        "appMenuUndo": "Retour",
        "appMenuRedo": "Avancer",
        "appMenuCut": "Couper",
        "appMenuCopy": "Copier",
        "appMenuPaste": "Coller",
        "appMenuSelectAll": "Tout sélectionner",
        "appMenuFind": "Trouver",
        "appMenuView": "Voir",
        "appMenuZoomIn": "Zoom avant",
        "appMenuZoomOut": "Zoom arrière",
        "appMenuActualSize": "Taille actuelle",
        "appMenuFullScreen": "Plein écran", //on some platforms, this string is replaced with one built-in to the OS
        "appMenuFocusMode": "Mode focus",
        "appMenuReadingList": "Liste de lecture",
        "appMenuDeveloper": "Developpeur",
        "appMenuReloadBrowser": "Recharger le navigateur",
        "appMenuInspectBrowser": "Inspecter le contenu",
        "appMenuInspectPage": "Inspecter la page",
        "appMenuWindow": "Fenêtre",
        "appMenuMinimize": "Réduire",
        "appMenuClose": "Fermer",
        "appMenuHelp": "Aide",
        "appMenuKeyboardShortcuts": "Raccourcis claviers",
        "appMenuReportBug": "Reporter un problème",
        "appMenuTakeTour": "Faire un tour",
        "appMenuViewGithub": "Voir sur GitHub",
        "appMenuAbout": "A propos de %n", //%n is replaced with app name
        "appMenuPreferences": "Préférences",
        "appMenuServices": "Services",
        "appMenuHide": "Cacher %n",
        "appMenuHideOthers": "Cacher les autres",
        "appMenuShowAll": "Montrer tout",
        "appMenuQuit": "Quitter %n",
        "appMenuBringToFront": "Tout mettre à l'avant"
    }
}

### CODE REVIEW

**Comment by PalmerAL** [comment]
Thanks for writing a translation! It looks like you deleted the en-US.json file, could you please add that file back?

**Comment by cubmann** [comment]
I don't really use github and I am lost using it. I think I only deleted it
in my copy of min this file is in the official folder of min on github.
Sincerely,
Victor

**Comment by PalmerAL** [comment]
No worries! You're correct that you only deleted it in your branch, but if I merge this PR, then all the changes in your branch (including deleting the file) get copied into the main Min repository.

If you're editing the files from your local computer, you can add the file back to your branch; see the instructions below. If you're editing the files from the GitHub website, I'm not sure how to do this; you could create a new branch and re-create the fr-FR.json file. Alternatively, if you don't want to do this, I'm happy to just take the contents of the fr-FR.json file and add them to the main Min repository; whichever way you want to do is fine.

Instructions if the repository is on your local computer:

1. Checkout the correct branch:

```
git checkout patch-1
```

2. Undo your last commit:

```
git reset HEAD~1
```

3. Add back the missing en-US.json file (you can just create a new file with the same name, and copy-paste the contents from here: https://github.com/minbrowser/min/blob/master/localization/languages/en-US.json).

4. Commit again:
```
git add .
git commit
```

5. Upload your changes to GitHub:
```
git push origin patch-1 --force
```

**Comment by cubmann** [comment]
Yes copy the content of fr-fr

**Comment by PalmerAL** [comment]
I've added the file in 58db31fd56e049f9d3e6e2138e41da6bc90cb678. Thanks for the translation!

**Pull request closed without merging**
