### PR TITLE
Add option to show task overlay when opening a window

### PR DESCRIPTION
**Pull request by PalmerAL**
@devgocri This implements your suggestion in #2278 (I've added the dock menu option in f7535a6f307fe05c4486098faa75572e4c17d444). 

This will still create a new blank task when the window opens; the reason is that the rest of the code assumes that the window always has some task selected in it, so we have to make a new task to give it something to select. This blank task will get reused across multiple window opens though, so the list won't get too cluttered.

### CODE REVIEW

**Comment by devgocri** [comment]
Hey @PalmerAL!

Just tested it - it works great! One issue though, if you close all open windows of Min, right click on the dock icon and select "New Window", it creates a new window but does not open task overlay as I've selected in settings. If I've already got a window of Min open however, it opens the task overlay as intended.

I'm really sorry for the late reply :C

**Comment by PalmerAL** [comment]
Thanks!

> One issue though, if you close all open windows of Min, right click on the dock icon and select "New Window", it creates a new window but does not open task overlay

Fixed.

> Also, spam opening multiple new windows create a whole bunch of new tasks instead of re-using existing tasks.

If you have multiple new windows, they all need their own task, since you can only have each task open in a single window. But if you make a window, select some existing task, then make a new window, it should reuse the blank task that was created for the first one.

**Comment by devgocri** [comment]
@PalmerAL Tested, works perfectly :D

**Comment by PalmerAL** [comment]
Thanks!

**Pull request merged**
