### PR TITLE
update Vietnamses Translation

### PR DESCRIPTION
**Pull request by raymondugv**
I've updated with my own Vietnamese skill.
Please check and tells if there is anything that could go wrong.

Could you please explain me the meaning of `bangs`?. This should help me a lot finding the correct translation for it.

Thank you.

### CODE REVIEW

**Comment by PalmerAL** [comment]
Bangs are shortcut commands that let you either search on a particular website (https://duckduckgo.com/bang) or perform some action in the browser (you can see a list by typing `!` in the searchbar).

I'll review the rest soon.

**Comment by raymondugv** [comment]
I've updated my  translation as well as fixed some error on last update.
Could you please check if the code is okay?.

**Comment by PalmerAL** [comment]
Sorry for the delay! Everything looks good.

**Comment by raymondugv** [comment]
> Sorry for the delay! Everything looks good.

@PalmerAL 
Glad to hear that.

Thank you very much.

**Pull request merged**
