### PR TITLE
Add save option on image right click

### PR DESCRIPTION
**Pull request by plrenaudin**
This allows the user to download the image.

**Warning**: it does not keep the image **name** and **extension**.
Any idea to improve this is welcome.

### CODE REVIEW

**Comment by PalmerAL** [comment]
Interesting, the image name and extension are saved for me (on OS X).

I'm guessing this menu item won't be used very often, so it probably makes more sense to get the web contents each time the menu item is clicked rather than on startup. That way, it won't take up memory and increase the startup time.

Other than that, looks good!

**Comment by plrenaudin** [comment]
I tested with a tricky situation where image filename is followed by a query string.
It may work correctly on some occasion.

**Comment by PalmerAL** [comment]
Can you please squash this into one commit?

**Comment by PalmerAL** [comment]
Looks good!

**Pull request merged**
