### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by miko-github**
Update importing (require from electron, fs , path) :star:  :heart:  :fist_raised:

### CODE REVIEW

**Comment by PalmerAL** [comment]
I don't think I agree with this change - it's not any shorter, and it's harder to read. With the old way, you can read the code, and see that `path` corresponds to `require('path')` for example. Now, you have to count how many items there are in the list to see which name matches each require() call.

**Comment by miko-github** [comment]
i first import main modules, then second module
for express i fist importing `express` and then `cors` `jwt`, and next `fs`,`path` and other things
this is my sort for any thing like this but actually i know and Accept :+1: :hugs:

**Comment by PalmerAL** [comment]
I still think it's easier to just have the module name and the `require` call on the same line, so I'm going to leave this as-is.

**Comment by miko-github** [comment]
# Hi :wave:,
if we add @babel then, that create any bug or problem?
i want to use @babel/cli and etc. to this project and change to `require` to `import`

that is impossible? :thinking:
:fist_oncoming:

**Comment by PalmerAL** [comment]
I'm not opposed to replacing Browserify with a different build system, but I think I'd want to analyze that more carefully before making a decision; it would be good to look at what alternatives there are to Babel first.

**Pull request closed without merging**
