### PR TITLE
Readme: Warn about late security updates

### PR DESCRIPTION
**Pull request by anko**
As explained in https://electron.atom.io/docs/tutorial/security/ and discussed in #440, Electron isn't made for writing browsers.  I think potential users deserve at least a note about it in the readme, as the general expectation otherwise is for web browsers to prioritise security.

This is just a suggested wording. Feel free to reword.

### CODE REVIEW

**Comment by apm** [comment]
This is like saying "Min is a minimal web browser that never should be used for that purpose".

**Comment by PalmerAL** [comment]
Hmm, I'm not sure I like linking to that page, because most of the problems it mentions don't apply to Min, as I mentioned in #440 (and I also don't think it's right to suggest that no one should ever use Min because of this). I'm thinking about this:

> Note: Min uses an older version of Chromium, which may be missing security fixes from later versions. [More Information](https://github.com/minbrowser/min/issues/440#issuecomment-338080554)

**Comment by anko** [comment]
@PalmerAL I like it!

**Comment by PalmerAL** [comment]
Great. Added in 1c28905ad7a14ed4cdad34daa1b47d73222a59d5.

**Comment by apm** [comment]
Maybe you could adjust the #440 title to be more gentle as well.  I reacted to 'Electron based browsers are insecure'.  Nobody wants an insecure browser.  To note that your browser may not have the latest security fixes since it lags behind Chromium releases is appropriate, but I'm under the impression that you do not think the browser is insecure, just less than optimal.  If it is insecure, then that needs to be addressed.  I think Electron should be more interested in keeping Chromium up to date, since the first thing people think when seeing the project is "Hey, I could make a custom browser with html and javascript... cool".

**Comment by PalmerAL** [comment]
Yeah, it probably does make sense to change the issue title to something better. To clarify what is mentioned there, it's hard to judge what "insecure" means exactly. Min definitely isn't as secure as using Chrome would be, but it's not horrible either; I don't think the risk from it is high enough that I would be concerned about using Min. Regarding Electron updates, it's tricky, because Electron is really closely integrated with the Chromium's internal API's, which are changing constantly with every release. Given the difficulty of upgrading (see this PR for example: https://github.com/electron/electron/pull/10213) and the amount of people working on Electron, they actually do a pretty decent job.

**Pull request closed without merging**
