### PR TITLE
add support for building windows installer

### PR DESCRIPTION
**Pull request by PalmerAL**

### CODE REVIEW

**Comment by PalmerAL** [comment]
@dbfreem @code-hunger @awesometech10 I have a working script to build a Windows installer for Min, would you be willing to try running the installer and make sure that it works? Download link: https://send.firefox.com/download/fdebe10b7fe8c00e/#36Q5R7I5nzcGhtYSV99YcQ

**Comment by PalmerAL** [comment]
Build with Electron 4, which should prevent any data loss: https://send.firefox.com/download/33070da16c220cf7/#3toVVz3yknkfYnZqipjPlg

A few things (like reader mode) might nor work correctly with this, since the master branch doesn't fully support Electron 4 anymore, but it should be enough to test whether or not the installer is working.

**Comment by AwesomeTech10** [comment]
Installer works well. It would be nice to integrate Squirrels autoUpdate functionality, however
    	
    	

    	Sent from my awesometech10@icloud.com email address.
    
  




On Mon, Apr 8, 2019 at 9:12 PM -0700, "PalmerAL" <notifications@github.com> wrote:












Build with Electron 4, which should prevent any data loss: https://send.firefox.com/download/33070da16c220cf7/#3toVVz3yknkfYnZqipjPlg


A few things (like reader mode) might nor work correctly with this, since the master branch doesn't fully support Electron 4 anymore, but it should be enough to test whether or not the installer is working.

**Comment by PalmerAL** [comment]
Thanks for testing that. Autoupdate would be nice; I haven't looked into it in a while, but it might be possible to do on Windows.

**Pull request merged**
