### PR TITLE
Disable back button when it's not active

### PR DESCRIPTION
**Pull request by revolter**
This makes the back button transparent when you can't go back because you're on the first page.

### CODE REVIEW

**Comment by revolter** [comment]
It looks like refreshing a tab causes the `canGoBack` method to return `true` instead of `false, and you can indeed go "back" to the same page. But I think this is another issue and not related to this PR.

**Comment by PalmerAL** [comment]
Thanks! A couple of suggestions:

* Since this function is called more often than just on navigations, maybe call it something like `updateBackButton`?
* Instead of directly setting the opacity, can we instead add and remove the `disabled` attribute of the button, and then have CSS that changes the opacity? That shoul dbe better for accessibility, and would also allow us to reuse the same styling for the other buttons if we want to.

I'm guessing that if this function is called from `did-navigate`, it's redundant to also call it from `onPageLoad`, but I haven't actually tested this, so feel free to leave it the way it is if it's necessary.

**Comment by PalmerAL** [comment]
I've opened a new issue about the reloading issue: #596.

**Comment by revolter** [comment]
Will update the PR tonight with those 2 changes.

> I'm guessing that if this function is called from `did-navigate`, it's redundant to also call it from `onPageLoad`, but I haven't actually tested this, so feel free to leave it the way it is if it's necessary.

For some reason, when opening up the browser, `did-navigate` is not called, so the back button doesn't get updated.

**Comment by revolter** [comment]
@PalmerAL, Updated 😃

**Comment by PalmerAL** [comment]
LGTM! I think I know what's causing the reloading issue, I'll try to fix that soon.

**Pull request merged**
