### PR TITLE
Fixes #1474. Bring Nodejs version in .nvmrc up to 12.18.3

### LINKED ISSUE #1474: "npm install" failed! ".nvmrc" probably needs update. What's the minimum version of node is required?
Hi, just found minbrowser and love it! Already found something that I feel I can contribute (bugs and translations). However, I'm currently stuck at "npm install" ........ Any help would be very much appreciated. Below is the basic environment:

- OS: macOS Catalina 10.15.7
- `nmv` is installed and and node is set to `8.1.4` automatically as specified by `.nvmrc`.
- `xcode` installed (full installation) and `SDKROOT` is set to `SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk`

When I run `npm install`, I'm getting the following error (part of the error output):

> keytar@7.3.0 build /Users/yulu/Workspace/minbrowser/node_modules/keytar
> node-gyp rebuild

```
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: glob dependency not found, set `options.disableGlob = true` if intentional
gyp ERR! stack     at defaults (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/node_modules/rimraf/rimraf.js:42:11)
gyp ERR! stack     at rimraf (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/node_modules/rimraf/rimraf.js:60:3)
gyp ERR! stack     at clean (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/lib/clean.js:11:3)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as clean] (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:41:37)
gyp ERR! stack     at run (/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:80:30)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:95:7)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:161:9)
gyp ERR! stack     at Function.Module.runMain (module.js:607:11)
gyp ERR! stack     at startup (bootstrap_node.js:158:16)
gyp ERR! stack     at bootstrap_node.js:575:3
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/yulu/.nvm/versions/node/v8.1.4/bin/node" "/Users/yulu/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/yulu/Workspace/minbrowser/node_modules/keytar
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! keytar@7.3.0 build: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the keytar@7.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

I tried to remove, reinstall, update `node-gyp` but no luck so far. It always fail for the same error. Really ran out of ideas. Can anyone help?

Thanks in advance!

### PR DESCRIPTION
**Pull request by yulucodebase**
Current Nodejs version in `.nvmrc` is too old (v8.1.4) and `npm install` fails because of this. 

This change bring the `.nvmrc` up the same version as the bundled Nodejs in Electron 11, which is what Min is currently based on.

### CODE REVIEW

**Comment by Milo123459** [comment]
Should be v14 for the ?? operator that is used.

**Comment by yulucodebase** [comment]
> Should be v14 for the ?? operator that is used.

Could you please elaborate a bit more what you meant by `?? operator`? Did you mean the new `??` operator in ES2020?

The reason I've only made `.nvmrc` to use `12.18.3` of Nodejs is to just align it with the Nodejs bundled with Electron.

Min is currently on Electron v11, and I believe it's bundled Nodejs is v12.18.3, [as it's been stated in its release note](https://www.electronjs.org/releases/stable?version=11&page=2#release-notes-for-v1100).

I think we should just keep the two in sync, instead of just going to whatever is the latest. We should upgrade `.nvmrc` whenever Min's Electron is upgraded.

**Comment by PalmerAL** [comment]
The versioning here is pretty confusing, but I think what's happening is that Electron is using the LTS versions of Node (which is currently v12), but with an upgraded version of v8. So if you downloaded nodejs v12 standalone, you'd get v8 7.8 or approximate, but Electron is using v12 with v8 8.7 (which means you still get support for the latest JS features).

I'm not sure what that means in terms of which version to pick, although as I mentioned before, it doesn't matter that much anyway because the version in `nvmrc` is only going to apply to the build scripts.

**Comment by Milo123459** [comment]
I say use latest because new features are cool. Even if electron supports it intellisense in code editors might not.

**Comment by yulucodebase** [comment]
Thanks guys for all the inputs! I'm still pretty new to JS but actually feel learnt a lot just being in these discussions.

It seems the two (Electron's embedded Nodejs vs the standard Nodejs)'s v8 engine are quite far apart:
Electron's v11 -> Nodejs v12.8.3 -> **V8 engine v8.7**
Standard Nodejs v12.8.3  -> **V8 engine v7.8**
Standard Nodejs v14.15.4 (LTS) -> **V8 engine v8.4**
Standard Nodejs v15.7.0 (Latest) -> **V8 engine v8.6**

Even the latest version of the standard Nodejs is falling behind Electron. In that case I think we should just go for the latest version in `.nvmrc`, like @Milo123459 suggested. 

We could also just remove`.nvmrc` and just say use whatever is the latest Nodejs for development in README. But that could create potential issues in the future, if the standard Nodejs takes over Electron in terms of V8 engine. So I think use `.nvmrc` to "enforce" the exact version of Nodejs is the safer option.

I'll update it to `15.7.0` if you all agree.

**Comment by Milo123459** [comment]
I'm all onboard with latest

**Comment by Milo123459** [comment]
^^ in the nvmrc you can do latest iirc

**Comment by yulucodebase** [comment]
OK, this is a bit annoying.

If the node version is changed to `15.0.0` or above, `npm install` automatically add two new dependencies:
```
"dependencies": {
    "dexie": "^3.0.3",
    "dragula": "^3.7.3",
    "electron-installer-debian": "^3.1.0", <<===========
    "electron-installer-redhat": "^3.2.0", <<===========
    "electron-squirrel-startup": "^1.0.0",
    "keytar": "^7.0.0",
    "mousetrap": "^1.5.3",
    "pdfjs-dist": "2.4.456",
    "regedit": "^3.0.3",
    "string_score": "^0.1.22"
  }
```

**Anything older than v15 seems fine**, e.g. currently LTS `v14.15.4`.

Shall we just go with `14.15.4` in this case as I don't think we want to change the project's dependencies? And I guess you also have the latest JS feature in `14.15.4` as well?

**Comment by Milo123459** [comment]
This is a known issue and just stash those changes, they are being moved from optional dependencies. Use yarn. Don't worry about it

**Comment by yulucodebase** [comment]
Cool! It's done now.

**Comment by PalmerAL** [comment]
This is fine with me!

**Pull request merged**
