### PR TITLE
Added a login prompt for basic http authentication.

### PR DESCRIPTION
**Pull request by NikSays**
Basic HTTP authentication is not very popular but often used in routers and other local network devices
Min had no prompt when site asked for authentication, so server always returned 401 (#174)
I added this using "prompt" event

### CODE REVIEW

**Comment by NikSays** [comment]
I just realized prompt title needs to be localized too. I will add this in next commit

**Comment by PalmerAL** [comment]
Thanks for working on this!

You don't actually need to create a new page for the dialog; instead, you should be able to do this:
```
createPrompt({
 text: ...,
 values: ...
}, function (result) {
    callback(result.login, result.password)
})
```

And the code in `prompt.js` will create the popup window and return the results for you.

**Comment by PalmerAL** [comment]
For the dialog strings, I would suggest:

* "Sign in to {site}" for the title
* "username" instead of "login"

**Comment by NikSays** [comment]
> you should be able to do this: createPrompt()
Thank you, this made everything much easier. I thought I needed to send an event from renderer.

**Comment by PalmerAL** [comment]
Everything looks good, thank you!

**Pull request merged**
