### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by Milo123459**
This just lints JS with standard, css with prettier

Adds command lint

### CODE REVIEW

**Comment by PalmerAL** [comment]
Files in `/ext` need to be excluded from formatting because they're imported from external repositories. Other than that, I think everything looks good.

**Comment by Milo123459** [comment]
> Files in `/ext` need to be excluded from formatting because they're imported from external repositories. Other than that, I think everything looks good.

+1, fixed

**Comment by PalmerAL** [comment]
I'm guessing the JS files in /ext would need to be excluded as well; prettierignore only applies to CSS, right?

The existing `test` command is this:
```
    "test": "standard --verbose js/**/*.js main/*.js",
```

So I think you could use the same path arguments for the lint command.

Also, can you revert the formatting changes in the `ext` directory?

**Comment by Milo123459** [comment]
The prettierignore ignores CSS linting, as thats what prettier is doing, linting css. I'll update the script, and reverting it might take a bit but I'll get to work.

**Comment by Milo123459** [comment]
@PalmerAL all fixed, you can go over it if you want

**Comment by PalmerAL** [comment]
Looks good to me!

**Pull request merged**
