### PR TITLE
Added uzbek language

### PR DESCRIPTION
**Pull request by avazkhan2808**
Added uzbek language.

### CODE REVIEW

**Comment by PalmerAL** [comment]
Looks good, thank you!

I'm adding a couple new strings in #971, would you mind translating those as well?

```
        "passwordManagerInstallerSetup": {
            "unsafeHTML": "First, download and run <a id='password-manager-setup-link-installer'></a>."
        },
         "passwordManagerSetupLinkInstaller": "the %p CLI installer",
         "secretKey": "Secret key" //missing translation
```

**Comment by PalmerAL** [comment]
I've tried adjusting the Windows language settings, and I can't actually get Min to display the translated version; can you try building Min with this change and confirm you can actually see the translations?

**Comment by avazkhan2808** [comment]
It's not working for me as well. I am on Linux and I changed system language to Uzbek but it doesn't seem to be working.

**Comment by PalmerAL** [comment]
I've opened an issue in Electron about this: electron/electron#23272

**Pull request merged**
