### PR TITLE
Update zh-CN.json. More translation for simplified Chinese language.

### PR DESCRIPTION
**Pull request by yulucodebase**
There are still some missing translations. I couldn't figure out how to actually access them on the UI so I can translate them with context. Will add more in the future hopefully.

### CODE REVIEW

**Comment by PalmerAL** [comment]
Thanks for doing this!

For the missing translations:

* Custom bangs: located at the bottom of the settings page
Screen Shot 2021-01-29 at 8 21 34 PM
("Bang" is a marketing word made up by DuckDuckGo)

* "settingsShowDividerToggle" is this option on the settings page:
* Screen Shot 2021-01-29 at 8 22 23 PM

* "settingsSeparateTitlebarToggle" is this: https://github.com/minbrowser/min/pull/977#discussion_r414918201

* "settingsUsageStatisticsToggle" is also a checkbox on the settings page.

* For the reader mode options, go to an article (like this one: https://www.nytimes.com/2021/01/29/business/elon-musk-gamestop-twitter.html), and click the book icon inside the tab.

* "passwordManagerSetupLinkInstaller" is the blue text in this dialog:

Screen Shot 2021-01-29 at 8 25 43 PM

**Comment by yulucodebase** [comment]
Thanks for the clarification @PalmerAL, I'll try to add these as well.

**Comment by yulucodebase** [comment]
Hi @PalmerAL , there seems no `settingsSeparateTitlebarToggle` option on my Preference page. Could you show me how to enable it? Thanks!

image

**Comment by PalmerAL** [comment]
That option only exists on Linux; there isn't any way to see it on macOS. But if it were there, it would just be another option in the "additional features" section.

**Comment by yulucodebase** [comment]
Thanks @PalmerAL. I can see it now on my Raspberry Pi. Should have actually checked the code first though.

**Comment by yulucodebase** [comment]
Hey @PalmerAL, I've now filled in all the missing translations for `zh-cn`. 

However, I feel there are some existing translation are either incorrect or not suitable for the context. I'll address these in this PR as well so please do not merge it yet. Thanks!

**Comment by yulucodebase** [comment]
OK, I've now push all the changes. I did a "fetch" and "pull" on upstream and now the commits looks a bit funny. 

There should be only 1 file changed. Did I just messed up my branch here?

**Comment by PalmerAL** [comment]
I think the branch just needed to be rebased; should be fixed now.

I don't see any more issues; thanks for doing this!

**Pull request merged**
