### PR TITLE
Modularize hosts list generation

### PR DESCRIPTION
**Pull request by code-hunger**
The hosts list are not exclusively bound to the urlParser. This way is more testable and reusable.

### CODE REVIEW

**Comment by PalmerAL** [comment]
Looks good to me! One (really minor) thing: can we avoid using if statements without braces? They do take up a bit less space, but it's not that much of a difference, and it makes it harder to see what is inside the if statement.

Also, do you mind making a list (either here or in the other issue) of what modules you're working on? I was planning to convert some more stuff in the next few days, but I want to make sure I don't unnecessarily duplicate something you're already working on.

**Comment by code-hunger** [comment]
Oh, sorry about the if-s. Fixed that. Currently I'm not working on anything, rather I have a few branches for which I'm just opening PRs separately so that it's easier for you to see the changes in each step.

After this, I have a tabState_refactor branch and then a webviewMenu_refactoring. I'll open a PR after you merge this with the next one, but will wait for you so that I can rebase on the latest changes and make it clean, otherwise you might run into merge conflicts.

**Comment by code-hunger** [comment]
BTW I was tempted to rewrite the function even more and completely remove its body by directly providing the return statent via the arrow syntax:
```
const truncatedHostsFileLines = (data, limit) =>
  data.length > limit
    ? data.substring(0, limit).split('\n').slice(0, -1)
    : data.split('\n')
```

But I decided I've probably gone too far... :)

**Comment by PalmerAL** [comment]
OK, good to know!

It is interesting how much you can shorten things with ES6, but I would agree we don't necessarily need to! Ultimately, making it readable is much more important.

**Pull request merged**
