### PR TITLE
Improve the Hungarian translation

### PR DESCRIPTION
**Pull request by gergo85**

### CODE REVIEW

**Comment by PalmerAL** [comment]
A lot of these seem like wording or grammar changes, can you explain more what the changes are? Was the grammar incorrect before?

**Comment by gergo85** [comment]
The translation contained many incorrect grammatical and spelling words.

**Comment by PalmerAL** [comment]
OK, thanks for fixing it!

**Comment by PalmerAL** [comment]
Also, it looks like there's a couple of translations that are still missing (settingsContentBlockingLevel, settingsEasyListCredit, settingsUpdateNotificationsToggle, customSearchEngineDescription, updateNotificationTitle), would you mind translating those as well? (the original strings are in en-US.json, in case you haven't seen them)

**Pull request merged**
