### PR TITLE
Add Raspbian(armhf) support, web browser and default browser settings for Debian based OS, update Korean strings.

### PR DESCRIPTION
**Pull request by lee-yunseok**
Add armhf build that works on Raspberry Pi 4 B Raspbian OS.
Update Korean translations.

### CODE REVIEW

**Comment by PalmerAL** [comment]
Thanks! This mostly looks good.

I haven't tried it yet, but I think it should be possible to share a singe script for both the Raspbian and the regular Debian build. If the arch for the `linux` target is set to `['x64', 'armv7l']`, then in the debian script here, `appPaths` should be an array with packages for both architectures:
https://github.com/minbrowser/min/blob/5b533a3bbf810cd757be7e8da9c75867f37079cb/scripts/buildDebian.js#L6-L7

You should then be able to loop over appPaths and create the installer for both packages.

The only thing that would possibly make the sharing not work is the `fpm` argument; I'm not entirely sure I understand what it's doing (and there aren't any references to it in the electron-packager source, so I don't see what it would be modifying). Can you clarify why that's necessary?

**Comment by lee-yunseok** [comment]
On Raspbian `armv7l` deb is not working so `fpm armhf` flag is required for install deb. https://github.com/electron-userland/electron-builder/issues/1230#issuecomment-491494976

**Comment by lee-yunseok** [comment]
Please don't merge until I mention, I'm working for merge Raspbian into Debian build. I've also written postinst and prerm script in Debian based OS to support the default web browser settings.

**Comment by lee-yunseok** [comment]
676231f will add Min to update-alternatives and will ask set Min as users default web browser at the installing deb package. Also remove Min on update-alternatives list when the user delete Min.

This working for Debian based OS including Raspbian. #230

**Comment by lee-yunseok** [comment]
@PalmerAL I've done this, failed merge build or script.

### I tried two ways:

- Merged one .deb
  - It will be installed on Raspbian but Min isn't working with exec error.
  - It couldn't install on Debian based without add-architecture by userside.
- Merged one buildDebian script
  1. Basically 'linux' build is amd64.
  2. I tried user input to define platform(linux or raspbian) and arch(amd64 and armhf) using async/await + redline, prompt, electron-promt.
  3. Input messages are appeard but electron this guy doesn't wait input and building, build failed by not defined platform. -This is natural because it's a building status.

**Comment by lee-yunseok** [comment]
- For testing Raspbian(ramhf) build: https://www.dropbox.com/s/x7kqioe4cpnyhjp/min_1.11.1_armhf.deb?dl=0
- For testing Debian(amd64) build: https://www.dropbox.com/s/yeh8v0z3z7s1yqk/min_1.11.1_amd64.deb?dl=0

**Comment by lee-yunseok** [comment]
a71c139 allows open Min browser from application's link to web or About and Help menu.

**Comment by PalmerAL** [comment]
Thanks for adding the defaults script!

Maybe the `buildRaspian` command could run the debian script with a `--raspbian`` argument, and the script could look for that and create a different packge? I can try to write it in a couple of days if you want.

**Comment by lee-yunseok** [comment]
Any argument can't work on Raspbian so I needn't argument, and other linux based may be the same.

**Comment by lee-yunseok** [comment]
Complete additional Korean strings.

**Comment by PalmerAL** [comment]
I think command-line arguments should work on Raspbian, can you explain what you mean?

This should solve the issue:

```diff
diff --git a/package.json b/package.json
index 9d46bb8..0931001 100644
--- a/package.json
+++ b/package.json
@@ -40,7 +40,7 @@
     "buildWindows": "npm run build && node ./scripts/buildWindows.js",
     "buildMac": "npm run build && node ./scripts/buildMac.js",
     "buildDebian": "npm run build && node ./scripts/buildDebian.js",
-    "buildRaspbian": "npm run build && node ./scripts/buildRaspbian.js",
+    "buildRaspbian": "npm run build && node ./scripts/buildDebian.js --raspbian",
     "buildRedhat": "npm run build && node ./scripts/buildRedhat.js",
     "buildAll": "npm run buildWindows && npm run buildMac && npm run buildDebian && npm run buildRedhat && npm run buildRaspbian",
     "updateFilters": "node ./ext/filterLists/updateEasylist.js"
diff --git a/scripts/buildDebian.js b/scripts/buildDebian.js
index 99e3ad8..530dc39 100644
--- a/scripts/buildDebian.js
+++ b/scripts/buildDebian.js
@@ -3,11 +3,13 @@ const debianInstaller = require('electron-installer-debian')
 const packageFile = require('./../package.json')
 const version = packageFile.version
 
-require('./createPackage.js')('linux').then(function (appPaths) {
+var isRaspbian = process.argv.some(arg => arg === '--raspbian')
+
+require('./createPackage.js')((isRaspbian) ? 'raspbian' : 'linux').then(function (appPaths) {
   var installerOptions = {
     src: appPaths[0],
     dest: 'dist/app',
-    arch: 'amd64',
+    arch: (isRaspbian) ? 'armhf' : 'amd64',
     productName: 'Min',
     genericName: 'Web Browser',
     version: version,
```

**Comment by lee-yunseok** [comment]
Wow, stupid. I never thought that. It works perfect.

**Comment by PalmerAL** [comment]
I've added one more new string; I promise this should be last one for a while.

**Comment by lee-yunseok** [comment]
Done. Thank you for add import feature.

**Comment by lee-yunseok** [comment]
Added descriptions for users in uninstall step. Feel free edit echo texts in postinst/prerm scripts what you want.

**Comment by lee-yunseok** [comment]
As #871, Koreans seem to want fully native Korean language. So I've worked for fully native Korean.

**Comment by lee-yunseok** [comment]
Done this work.

**Comment by lee-yunseok** [comment]
Doen this work.

**Comment by PalmerAL** [comment]
I think everything looks good! I don't have a Pi to test this on at the moment, but the Debian build seems to work, and I don't see any more issues.

Thank you!

**Comment by lee-yunseok** [comment]
@PalmerAL Don't worry about the Pi because I've already tested it. Raspbian also has desktop versions so I think it would be nice if you write a description of the **BuildRaspbian** is **Raspberry Pi** build in the README.

**Comment by PalmerAL** [comment]
done.

**Comment by PalmerAL** [comment]
Also, can you let me know what the values of `navigator.platform` and `navigator.userAgent` are on the Pi so that I can add download links for the raspbian build to the website?

**Comment by lee-yunseok** [comment]
navigator.userAgent = Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.94 Safari/537.36
navigator.platform = Linux aarch64

**Comment by PalmerAL** [comment]
Thanks, the download button on the website should work now.

**Comment by lee-yunseok** [comment]
It working, thanks!

**Pull request merged**
