### PR TITLE
Show forward button on hover

### PR DESCRIPTION
**Pull request by PalmerAL**

### CODE REVIEW

**Comment by PalmerAL** [comment]
@lubiedo Let me know what you think. (Github wouldn't let me mark you as a reviewer; I just added you to the repository so that should work in the future).

**Comment by lubiedo** [comment]
Looks really good and code looks clean. There's only one (small) detail which is the horizontal scrollbar under the tabs that it gets visible for a second. Maybe disabling the overflow while the mouse is over the buttons will avoid this behavior?

https://user-images.githubusercontent.com/63729414/123441480-24d75c80-d591-11eb-961d-867f37e9c8ac.mov

If this is not an issue then I think that it can be merged!

**Comment by PalmerAL** [comment]
Thanks for pointing that out! I've done what you suggested in b27b5315bc5869e3b640f8aa3da34207a3df0994 - let me know if you see any more issues after that.

**Comment by lubiedo** [comment]
Yep, that did the trick. Did some tests and looks really good.

**Review by lubiedo — APPROVED** [review]

**Comment by PalmerAL** [comment]
Great!

**Pull request merged**
