### PR TITLE
Remove settings.js from the legacy modules list and fix imports

### PR DESCRIPTION
**Pull request by code-hunger**
`settings.js` no more needs to be concatenated with the others. I used the same technique from settings.js to check if the page is loaded in the browser from an html file or not, in order to decide whether to import settings.js or not. Otherwise one part of the browser was giving an error about `settings` being undefined.

### CODE REVIEW

**Comment by code-hunger** [comment]
Actually I just thought about a way to allow the usage of const instead of var by removing searchEngine from the list, too. I don't have the time to do it now so I'll check it in a few hours.

**Comment by code-hunger** [comment]
For now it'll be too hard to fix that alone - we need to isolate a few other components before we're able to do it cleanly. I've already started working on it on another branch to keep it simple and clear, but it's far from ready. Let's proceed it piece by piece :)

And btw, doing this refactoring & investigation of browser internals makes me udnerstand how it works much more deeply. Quite an interesting task :)

**Comment by code-hunger** [comment]
I just saw there was a request for a tab duplicate feature, decided to give it a shot here.

**Comment by PalmerAL** [comment]
In order to do this correctly, we'd also need to import `settings.js` from all the other places that use it - filteringRenderer.js, keybindings.js, menubarVisibility.js, goBackButton.js, phishingWarning.js, and probably some other ones. For now, this happens to work, because searchEngine.js is loaded in the global scope, and so once it loads `settings.js`, all the other code in the global scope will be able to access it as well, but this won't work once `searchEngine.js` is itself a module. The way I've been solving this for the other modules is to just do `var settings = require("settings.js")` at the top of each global script, and let them all overwrite each other. Browserify will bundle the scripts so that there is still only one instance of `settings`, and this way we can reduce the amount of breakage that will happen later.

**Comment by PalmerAL** [comment]
I think the duplicate tab addition looks good for the most part; could you split that into a separate PR?

**Comment by PalmerAL** [comment]
Settings.js was converted to a module as part of #766, so this isn't necessary any more.

**Pull request closed without merging**
