### PR TITLE
Fix: shift+letter not registering as single letter shortcut

### PR DESCRIPTION
**Pull request by joeysnclr**
Fixes issue #1231 

My approach simply discards "shift+" from the string that is being tested. I am not so experienced with regex so there is probably a better way to exclude shift+ instead of .replace.

### CODE REVIEW

**Review by Syndamia — APPROVED** [review]
Seems like a fine change. Couldn't find problems after a bit of testing.

**Comment by PalmerAL** [comment]
If you want to use a regex, this should work:

```
/^(shift)?\+?\w$/
```

**Comment by joeysnclr** [comment]
Thank you that regex was exactly what I was looking for.

This bug is now fixed.

**Comment by PalmerAL** [comment]
LGTM, thanks.

**Pull request merged**
