### PR TITLE
This commit adds visual feedback while the page is loading

### PR DESCRIPTION
**Pull request by danfragoso**
When using this browser on a slow connection i've missed some feedback if the page was loading or not.

captura de tela 2017-11-18 as 13 20 58

### CODE REVIEW

**Comment by PalmerAL** [comment]
I like the idea of showing some kind of progress bar while the page is loading, but it's kind of distracting to have the icons in the tab suddenly shift when clicking a link.

I wonder if an actual bar (maybe just a thin line under the tab, like in https://github.com/minbrowser/min/issues/52#issuecomment-212186989) would work better.

**Comment by danfragoso** [comment]
Maybe it is, i will try to work on the bar.

**Comment by danfragoso** [comment]
I've changed it, the behavior now is similar to safari.

**Comment by PalmerAL** [comment]
I like it! I'll add some commits to fix a few minor issues I've noticed.

One thing I'm wondering about is that on a page that loads pretty quickly, the progress bar seems to make the page load feel slower. I'm wondering if it would make sense to do something like we do on the PDF viewer, where we show no progress bar at all for the first couple seconds, and then move to the p25 state if the page still hasn't loaded. That way, pages that load quickly would still seem to just appear without any wait, and for pages that take longer to load, you would still get feedback that the page is loading. What do you think?

**Comment by danfragoso** [comment]
That would be great, but i don't really have the time to do it for now. It would be nice if you did it.

**Comment by PalmerAL** [comment]
OK, that's fine, I will do it.

**Comment by danfragoso** [comment]
Nice, thanks!

**Comment by PalmerAL** [comment]
I think I've finished everything, so I'm going to go ahead and merge this. Let me know if you notice something that should be changed.

**Pull request merged**
