### PR TITLE
Fix issue #1720

### PR DESCRIPTION
**Pull request by lubiedo**
Check if the item filename differs from the basename in path and update
the name in the download bar.

### CODE REVIEW

**Comment by PalmerAL** [comment]
I think the filename calculation should happen once at the beginning of the `else` block, and then be used for both IPC calls. The call on line 26 makes the item appear initially, and then `item.on('updated')` happens every time the item's download progress changes (once or twice a second).

Also, we don't need to call `item.getFilename()` at all any more, right? It could just be `name: savePathFilename`.

BTW, your last few commits don't have an email address associated with them - if you set it with `git config`, GitHub will associate them with your account.

**Comment by lubiedo** [comment]
The thing is that, for what I've tested, `item.getSavePath()` is not really defined until the user selects a path or changes the name and falls into the `updated` event.

**Comment by PalmerAL** [comment]
Oh, right - I was thinking that the file starts downloading after the save dialog is closed, but the download actually starts before that. This is the right fix then.

GitHub still isn't linking your commits - there's a missing `.com` at the end of the email:


But it doesn't matter too much for this, so I'm going to go ahead and merge.

**Comment by lubiedo** [comment]
Oh, dammit! Will fix that

**Pull request merged**
